### ISSUE TITLE
Integrate ICT documentation

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#102]
### Description
ICT documentation should be integrated in the documentation portal. The is currently no documentation on ICT, there is a blog post, and there is a generated API reference:
https://qubiota.com/ict-rest/

In the future, the documentation could be generated and take the same path client libs with integration to BuildKite. But for now, it would be enough to create an overview page that links to the reference. @mikrohash can provide the initial information and context to build that page. 

This is also a good opportunity to change the IRI section of the docs site into a something more general. Node software in general. This will at some point be extended by Entangled/cIRI anyway. 

There could be an experimental node software section under node software, for example, where ICT can live now. This needs to be thought through from the perspective of general inf. architecture.

**Comment by JakeSCahill** [comment]
This would also be a good place for a concept article that discusses the difference between IoT and the Internet. It'd be useful to discuss the reasons for developing ICT and discuss the natural progression of IOTA. This way all of these concepts (ICT cIRI, IRI) will mean something to users and they will understand the differences among them.

What do you think @jakubcech ?

**Comment by NelsonPython** [comment]
ICT is part of the Qubic project which has these components:
-Qubic
-Qubic Computation Model (QCM)
-Iota Control agenT (ICT) - light-weight node, called a “Q-Node”
-Iota eXtension Interface (IXI)
-Abra dataflow language
-QUPLA - QUbic Programming Language

Let's consider how to address the entire Qubic suite - one Qubic index item or an index item for each tool?

**Comment by jakubcech** [comment]
I think that sounds great @JakeSCahill, a landing page for all the node software like this makes sense. 

@NelsonPython, I'm not sure whether we should treat it as such right now. But in the future perhaps so. Right now people are running ICT nodes out of interest and for testing. We don't really much of content to provide for the other parts Qubic at this point I think? But it definitely needs to be considered for the future.

**Comment by JakeSCahill** [comment]
ICT 0.5 is due to be released soon. I think it's worth waiting until that's released until we add an installation article to the site.

**Comment by JakeSCahill** [comment]
#173

**Comment by JakeSCahill** [comment]
Closing this for now. We have a node software section and Ict will become Bee.

Bee docs will follow when it's released.
