### ISSUE TITLE
Mention that IRI should be used with a reverse proxy

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#107]
### Description
The guide for running an IRI node should contain a recommendation to also set up a reverse proxy with for example Nginx or Haproxy. https://docs.iota.org/docs/iri/0.1/how-to-guides/run-an-iri-node-on-linux 

Both the Playbook from Nuriel and IOTA Partners use this approach. We can link to that. 

We should also mention that the proxies should be recommended for API rate limiting.

**Comment by JakeSCahill** [comment]
@jakubcech added a guide to setting up a reverse proxy for Linux servers #116 

This doesn't include extra steps for Docker.
