### ISSUE TITLE
Error when named HTML links in Markdown files are used

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/documentation#117]
When I run 
```
node buildProjects
```
it outputs the following error:
```
ERROR: HTML Links should be converted to Markdown: '../references/iri-configuration-options.md#local-snapshots-depth' in 'iri/0.1/references/data-in-the-snapshot-metadata-file.md'
```

So, I looked into it. There are some named HTML links. I get the idea behind it. So, if you link to the page, the browser scrolls down to the part you are referring to. From a UX standpoint that is really good and I would not remove it. But since the Validator throws some Errors, we should change something. 

Maybe changing the validator, so that it doesn't run into an error. (If I take a look into the Markdown Specifications, HTML links are also fine)
or find another solution which is not depending on HTML links.

**Comment by obany** [comment]
The error is correct the document has:

```
<a href="../references/iri-configuration-options.md#local-snapshots-depth"><code>LOCAL_SNAPSHOTS_DEPTH</code></a>
```

Where as it should be

```
[`LOCAL_SNAPSHOTS_DEPTH`](../references/iri-configuration-options.md#local-snapshots-depth)
```

**Comment by Citrullin** [comment]
@obany Sorry, you are completely right. I should read the error carefully before checking the document. I missed the document or line. I am not sure anymore :) The a with a name does not throw any error :D
