### ISSUE TITLE
Using blockquotes instead of dl & dt tag

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/documentation#118]
The current glossaries contain the following structure:
```
<dl><dt>Headline</dt><dd> Description
```

So I looked into the frontend and the block looks like a blockquote to me. So, how about using complete markdown without HTML for it? The rest is just interpretation magic :) Like this:

```
> **_Headline_**
> _Description_
```

**Comment by obany** [comment]
I have added an issue to the platform repo to see if we want to style these differently or not

https://github.com/iotaledger/documentation-platform/issues/205
