### ISSUE TITLE
Create a seed

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/documentation#126]
https://docs.iota.org/docs/getting-started/0.1/tutorials/create-a-seed
It would be good to add the information that you can also create a seed in Trinity to this site, 
because you might be annoyed otherwise, if you see on the next page, that it's also possible in Trinity

**Comment by JakeSCahill** [comment]
Good point. Thanks @Thoralf-M

**Comment by JakeSCahill** [comment]
Made a few changes including a fix for this issue in this PR: https://github.com/iotaledger/documentation/pull/132/files
