### ISSUE TITLE
Split architecture documents in blueprints

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#153]
### Description
Jake: Blueprint architecture page should be split so that it only includes conceptual information about the architecture we use in the blueprint and possible changes you may want to make in your own implementations.

The implementations themselves should go into a 'technical implementation' (something like that) article. In architecture, we can explain what the code does to help users to navigate the code on GitHub and learn where to make changes.

Follows #115

**Comment by JakeSCahill** [comment]
Taking a look at the blueprints in more detail, I think the structure we have seems to work. What do you think @jakubcech ?
