### ISSUE TITLE
Add static IP address to cIRI documentation

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/documentation#156]
Just for myself. Got some feedback.
Add the need of a static IP address to the cIRI documentation. Similar to the IRI one.

**Comment by JakeSCahill** [comment]
We have an article in `general` about exposing a local device to the Internet. Maybe you could link to that too.

**Comment by Citrullin** [comment]
@JakeSCahill Good point. I added it to my PR. #166

**Comment by l3wi** [comment]
Merged
