### ISSUE TITLE
Find a better way to display the Data In The Ledger

### ISSUE THREAD

**Issue by obany** [iotaledger/documentation#172]
This content https://github.com/iotaledger/documentation/blob/develop/iri/0.1/references/data-in-the-ledger.md looks OK on Github

![image](https://user-images.githubusercontent.com/5030334/53619318-fc790680-3bff-11e9-910f-88ac5e96dbd7.png)

But on the docs site it is very hard to read with lots of blank space and all the important info squashed into the last column

![image](https://user-images.githubusercontent.com/5030334/53619326-0d297c80-3c00-11e9-9deb-586a4c5ffc24.png)

**Comment by JakeSCahill** [comment]
You're right, it's a bit ugly 😅 
I think I'll pull the metadata out into its own table.

**Comment by JakeSCahill** [comment]
#174
