### ISSUE TITLE
Some text is too long for table columns

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#199]
### Description
Some names are too long for the table if all columns have the same width:
https://docs.iota.org/docs/hub/0.1/references/api-reference
https://media.discordapp.net/attachments/502455245620641792/557293013664006145/unknown.png

This might be a little difficult to resolve, or we may just need to force a break line in words above a certain length...

**Comment by obany** [comment]
We can try and do this automatically by applying `overflow:auto` to table cells and it will look like this

![image](https://user-images.githubusercontent.com/5030334/54596916-a94be400-4a46-11e9-8dc9-1ceee9f984d7.png)

Or we can apply `word-break:break-all` to the cell content and it will look like this

![image](https://user-images.githubusercontent.com/5030334/54596982-c7194900-4a46-11e9-8842-391adb2e7321.png)

We would have to double check that it looks good for all other data if we make a significant styling change like this.

**Comment by JakeSCahill** [comment]
I think I prefer the word break rather than the extra scroll bar. It's much easier to scan and is less effort for a user.

**Comment by obany** [comment]
Fixed in the theme here https://github.com/iotaledger/iota-css-theme/commit/c3daddf4ff1f52eb28940d876cb2044287f890ca
