### ISSUE TITLE
getTransactionsToApprove: wrong references parameter

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/documentation#223]
It is said [here](https://docs.iota.org/docs/iri/0.1/references/api-reference#gettransactionstoapprove) that `getTransactionsToApprove` request has a `references` parameter.

It is actually a single `reference` parameter as can be seen [here](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/API.java#L425). 

Both description of the parameter and examples are false.

**Comment by JakeSCahill** [comment]
Thanks for the heads-up 👍 Will update it

**Comment by JakeSCahill** [comment]
#224
