### ISSUE TITLE
Blueprint landing page

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#226]
### Description
Blueprints will be sent around and presented to 3rd parties quite a lot. Also, there will be quite a lot more in the future, authored by others, not just IF. We should think about making the presentation a little more polished. 

**One idea**:
Maybe a landing page for the overview of Blueprints, where each blueprint would have a representing thumbnail, done by Sabri and a short description. 

We shall see if the format of the normal content page is sufficient, but it probably should. Something like client library landing page, but with thumbnails and a short description for each.

This may require a new 'thumbnail' artifact to be formattable through our markdown convention.

**Comment by JakeSCahill** [comment]
The same thing for a 'Node software' page would be great too. Then, we can host docs for IRI, Ict and cIRI.

**Comment by jakubcech** [comment]
Andrew will start by creating a design for this before it can be picked by to convert to a markdown template. This will be reusable for any kind of landing page that wants to use an image + short text presentation. We'll see what the layout we land on is based on Andrew's proposal. 

The page will be the same as any other content page otherwise and since it will be just a markdown formatting template, it can have arbitrary content before and after. 

The menus on the left and right are also maintained.

**Comment by jakubcech** [comment]
Assigning to Andrew for the first step of the process. :)
