### ISSUE TITLE
Clicking a pic doesn't show the larger pic

### ISSUE THREAD

**Issue by gjeee** [iotaledger/documentation#227]
e.g. on https://docs.iota.org/docs/blueprints/0.1/p2p-energy/architecture

i would expect to see a larger pic when clicking on one.

**Comment by obany** [comment]
This functionality is included, see animation below

![App-architecture-_-P2P-energy-grid-_-App-Blueprints-_-IOTA-Documentation-Google-Chrome-2019-03-29-07](https://user-images.githubusercontent.com/5030334/55209862-be1e3980-51f5-11e9-84d5-8061e84ee10a.gif)

If this is not working for you could you give some more details e.g. browser, device etc
Or is it a specific image that doesn't work ?

**Comment by gjeee** [comment]
hhmm weird...is it browser-related then? i run firefox 66.0.1 (64-bit) on my dekstop

**Comment by obany** [comment]
Just tested in Firefox and there something a little odd going on, the image popup does appear but with no image.

**Comment by obany** [comment]
Fixed in this PR https://github.com/iotaledger/documentation-platform/pull/224
Should work in the next build.

**Comment by gjeee** [comment]
great!!!! love quick fixes :-)
