### ISSUE TITLE
attachToTangle: bad minWeightMagnitude parameter type

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/documentation#228]
`attachToTangle` documentation on https://docs.iota.org/docs/iri/0.1/references/api-reference#attachtotangle shows `minWeightMagnitude` request parameter as a string while it should be an integer.

**Comment by JakeSCahill** [comment]
@thibault-martinez Aded a fix to this in #225 

Thanks 👍

**Comment by thibault-martinez** [comment]
Alright, cool, you can close then :)
