### ISSUE TITLE
api: duration should be an integer

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/documentation#243]
In endpoints https://docs.iota.org/docs/iri/0.1/references/api-reference#addneighbors and https://docs.iota.org/docs/iri/0.1/references/api-reference#getinclusionstates, `duration` fields of the responses are shown as string instead of integers.

**Comment by JakeSCahill** [comment]
Fixed in #225 thanks

**Comment by thibault-martinez** [comment]
Whoops, sorry, will try to check open PRs next time.
