### ISSUE TITLE
Document `getTrytes` API call behavior after snapshot

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#265]
### Description
The current behavior of the `getTrytes` API call after a snapshot has been taken is not documented. Calls to getTrytes for transactions removed in the snapshot start to return payloads of all 9s.

`GetTrytes` is always meant to return a list of trytes equalling the length of requested hashes and if there's any hash that's not in the db, it will fill it up will all 9s.

**Comment by JakeSCahill** [comment]
#270
