### ISSUE TITLE
Create the personas

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#27]
Define the personas that will be using the website. 

For some user stories, the persona may be an internal customer (when we define how other repos should generate content), but I'm not sure we need a long term persona for that. 

We have a first stab at the personas. Let's go through them and see if anything is missing there. 

Personas:
https://docs.google.com/spreadsheets/d/1-9fcYpiikpYTU2UgpWJEAAd3yVsQcjFW15Z7LX3wvnM/edit#gid=0

**Comment by jakubcech** [comment]
Think we can go with what we have at this point. :)

**Comment by farmanp** [comment]
Not necessary to reopen but just for pure discussion - are there actionable user stories to address the issues?
