### ISSUE TITLE
Include information about used addresses under Trinity docs

### ISSUE THREAD

**Issue by t00k** [iotaledger/documentation#273]
In Trinity docs, related to the _view addresses_ page there should be information about _used addresses_.

This page; https://docs.iota.org/docs/trinity/0.1/how-to-guides/manage-your-account#view-the-addresses-of-an-account

need information on what a used address is and what this means.

Something a long the lines of;
_Used addresses is identified with their red color and strikethrough. This means that the address is used and should not contain funds. blah blah blah.._

Today this was posted in one of the Discord channels which spawned this idea.

> iotadaev Idag 19:16
> What does it mean if some of the addresses in the overview are red and strikethrough? Cant't find information in the documentation about that.

**Comment by JakeSCahill** [comment]
#274 

Thanks @t00k
