### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/documentation#28]
This repo should be [archived](https://help.github.com/articles/archiving-repositories/) to avoid confusion with https://github.com/iotaledger/docs. This will prevent new issues and pull requests from being submitted.

CC: @anyong @l3wi

**Comment by jakubcech** [comment]
Will be used for a new docs site project, so we actually want new stuff in here. :) But will try to make it clear in the Readme file. Thanks!

**Comment by rajivshah3** [comment]
Ah whoops, sorry 😃
