### ISSUE TITLE
Decide on the rendering framework

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#30]
### Description
Consider different options and weigh in the requirements. Please keep this a live discussion on Slack and here.

Alexey/Marwen

**This task should yield a write-up of the existing platforms and how they meet our requirements.**

- [ ] Server-side rendering. 
- [ ] Ability to handle multiple products.
   - Ability to apply different themes based on the product. 
- [ ] Should make use of markdown format that is easily editable. A user should always be just one click away from suggesting a change to the page and any user persona should be able to figure out how to make changes to content. 
- [ ] Support for easy structuring into a navigation/menu. 
    - Support for linking into the same page from multiple points. 
    - Nesting.
    - Programmatic control over how many levels we can have.  
- [ ] Documentation users need to be able to suggest where a new file they create lives in the navigation without having to modify any other file. (not a strong requirement - we can handle this part ourselves when merging PRs at first.)
- [ ] Support for embedding **interactive** elements - custom react components and support for code snippets. Interactive elements for JS at least. This can be just embedded element from another website. 
- [ ] Should be able to display files generated by other repos (currently MD). We are rendering IRI docs in markdown now. iota.js is also done in markdown. 
- [ ] The solution should have as few external dependencies as possible.
- [ ]  Support for mobile. 
- [ ]  Support for users to provide feedback without having to create a PR.
- [ ]  Support for providing suggestions on what is missing on the page. 
- [ ] Support for versioning. We will want versioning later on. 

Later on - support for interactive python and other languages. 

### Open questions 
- Are we going to use nextjs like we did up until today with MDX? Are we going to use Gatsby? 
- What file formats we're going with. Standard MD? What is the downside when we go for the ability to render interactive elements? More difficult rendering?

**Comment by sobolev-alexey** [comment]
Build test project with [react-static](https://github.com/nozzle/react-static)
Test project is deployed and available [here](https://iota-documentation.firebaseapp.com).

It is 
* Server-side rendered
* Fully interactive and provides full React support
* Able to handle multiple products
* Makes use of markdown format 
* Supports different search libraries. Currently runs with `Lunr.js`, later can be updated to use `Algolia`
* Provides support for easy structuring into a navigation/menu.
* Has general support for mobile, however some adjustments are required
* Has relatively few external dependencies.

**Comment by mtrabelsi** [comment]
@sobolev-alexey can you put the source, because its important to see how is difficult to maintain the doc and evaluate it.

**Comment by sobolev-alexey** [comment]
@mtrabelsi https://github.com/iotaledger/documentation/tree/react-static

**Comment by jakubcech** [comment]
Gatbsy is a NO-GO - it's not performant enough.

**Comment by jakubcech** [comment]
We've concluded on https://github.com/iotaledger/documentation/tree/react-static :) Thanks!
