### ISSUE TITLE
Change title of "Create an IOTA network" to "Set up a Private Tangle"

### ISSUE THREAD

**Issue by jnpsbck** [iotaledger/documentation#372]
"Private Tangle" is more commonly used and searching for "private" or "private tangle" on the docs platform won't get me to the page where I can find out how to set up a private tangle.

**Comment by JakeSCahill** [comment]
We'll be updating the homepage as well soon. Will definitely change the label of 'Compass' to something more concrete like 'Private Network' or 'Private Tangle'.

**Comment by HolgerKoether** [comment]
Let's also add it to the popular topics
