### ISSUE TITLE
Setting up a ZMQ feed to an IRI node in IOTA Go

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#532]
Creating a full scenario on setting up a ZMQ feed to an IRI node and filtering transactions with a certain tag in the IOTA Go. Use the library to inspect the data in the feed.

If you implement this one library language, please post the results in the other tasks so that others can follow the same approach.

**Comment by JakeSCahill** [comment]
https://github.com/iotaledger/documentation/blob/develop/client-libraries/0.1/how-to-guides/go/listen-for-transactions.md
