### ISSUE TITLE
Create an integration with powbox and faucet on devnet in IOTA JS

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#538]
### Description
Create a full scenario describing how to create an integration with PoWBox and faucet on Devnet using the JS client library.

If you implement this one library language, please post the results in the other tasks so that others can follow the same approach.

**Comment by JakeSCahill** [comment]
@jakubcech do we still have the PoWbox? https://powbox.testnet.iota.org/ is a dead link.

**Comment by JakeSCahill** [comment]
Going to close this as PoWbox is no longer available.
