### ISSUE TITLE
Creating a re-attachment and promotion service in IOTA JS

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation#546]
### Description
A full walk through on how to create a re-attachment and promotion service using the JS Client library.

If you implement this in one library language, please post the results in the other tasks so that others can follow the same approach.

**Comment by JakeSCahill** [comment]
https://github.com/iotaledger/documentation/blob/develop/client-libraries/0.1/how-to-guides/js/confirm-pending-bundle.md
