### ISSUE TITLE
Add how-to guides for C client library

### ISSUE THREAD

**Issue by JakeSCahill** [iotaledger/documentation#578]
These guides should follow the code here: https://github.com/iota-community/c-iota-workshop

**Comment by oopsmonk** [comment]
Here are API examples as well: https://github.com/iotaledger/entangled/tree/develop/cclient/api/examples

**Comment by JakeSCahill** [comment]
https://github.com/iotaledger/documentation/tree/develop/client-libraries/0.1/how-to-guides/c
