### ISSUE TITLE
Compass needs the Deprecation notice

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/documentation#825]
**Describe the bug**
Compass (as IRI) is deprecated.
It is necessary to add the deprecation notice to Compass documentation to avoid confusion.

**Expected**
Add 

```
:::danger:
This software is now **deprecated**. See [Set up a private Tangle as a Hornet plugin
](root://hornet/1.1/tutorials/set-up-a-private-tangle-hornet.md) for an up-to-date private Tangle.
:::
```
To the documentation related to Compass

**Additional context**

**Comment by huhn511** [comment]
LGTM!

Shipped to master: https://docs.iota.org/docs/compass/1.0/overview?q=compass&highlights=Compass

closed by #826
